var svg = d3.select("body").select("#svg_BarChart3");
var data = [
  {id: "Blue", date: "June 12", shares: 130},
  {id: "Red", date: "June 12", shares: 119},
  {id: "Grey", date: "June 12", shares: 86},
  {id: "Red", date: "June 12", shares: 76},
  {id: "Blue", date: "June 12", shares: 68},
  {id: "Blue", date: "June 12", shares: 66},
  {id: "Purple", date: "June 12", shares: 63},
  {id: "Red", date: "June 12", shares: 56},
  {id: "Red", date: "June 12", shares: 55},
  {id: "Grey", date: "June 13", shares: 68},
  {id: "Blue", date: "June 13", shares: 59},
  {id: "Red", date: "June 13", shares: 57},
  {id: "Blue", date: "June 13", shares: 53},
  {id: "Blue", date: "June 13", shares: 53},
  {id: "Red", date: "June 13", shares: 44},
  {id: "Blue", date: "June 13", shares: 29},
  {id: "Blue", date: "June 13", shares: 28},
  {id: "Grey", date: "June 13", shares: 25},
  {id: "Blue", date: "June 13", shares: 25},
  {id: "Grey", date: "June 14", shares: 65},
  {id: "Red", date: "June 14", shares: 31},
  {id: "Blue", date: "June 14", shares: 24},
  {id: "Red", date: "June 14", shares: 24},
  {id: "Blue", date: "June 14", shares: 22},
  {id: "Blue", date: "June 14", shares: 17},
  {id: "Blue", date: "June 14", shares: 17},
  {id: "Purple", date: "June 14", shares: 16},
  {id: "Blue", date: "June 14", shares: 16},
  {id: "Red", date: "June 14", shares: 13},
  {id: "Grey", date: "June 15", shares: 103},
  {id: "Purple", date: "June 15", shares: 98},
  {id: "Blue", date: "June 15", shares: 75},
  {id: "Red", date: "June 15", shares: 75},
  {id: "Blue", date: "June 15", shares: 59},
  {id: "Blue", date: "June 15", shares: 42},
  {id: "Blue", date: "June 15", shares: 35},
  {id: "Purple", date: "June 15", shares: 29},
  {id: "Purple", date: "June 15", shares: 23},
  {id: "Blue", date: "June 15", shares: 22},
  {id: "Grey", date: "June 16", shares: 77},
  {id: "Purple", date: "June 16", shares: 57},
  {id: "Red", date: "June 16", shares: 33},
  {id: "Blue", date: "June 16", shares: 28},
  {id: "Blue", date: "June 16", shares: 21},
  {id: "Blue", date: "June 16", shares: 20},
  {id: "Red", date: "June 16", shares: 20},
  {id: "Blue", date: "June 16", shares: 20},
  {id: "Red", date: "June 16", shares: 19},
  {id: "Blue", date: "June 16", shares: 18},
  {id: "Blue", date: "June 17", shares: 97},
  {id: "Grey", date: "June 17", shares: 78},
  {id: "Red", date: "June 17", shares: 36},
  {id: "Red", date: "June 17", shares: 35},
  {id: "Blue", date: "June 17", shares: 21},
  {id: "Red", date: "June 17", shares: 20},
  {id: "Blue", date: "June 17", shares: 18},
  {id: "Blue", date: "June 17", shares: 16},
  {id: "Blue", date: "June 17", shares: 14},
  {id: "Red", date: "June 17", shares: 14},
  {id: "Grey", date: "June 18", shares: 61},
  {id: "Blue", date: "June 18", shares: 41},
  {id: "Blue", date: "June 18", shares: 21},
  {id: "Purple", date: "June 18", shares: 20},
  {id: "Blue", date: "June 18", shares: 19},
  {id: "Red", date: "June 18", shares: 18},
  {id: "Blue", date: "June 18", shares: 17},
  {id: "Red", date: "June 18", shares: 15},
  {id: "Red", date: "June 18", shares: 12},
  {id: "Red", date: "June 18", shares: 11},
  {id: "Red", date: "June 19", shares: 87},
  {id: "Grey", date: "June 19", shares: 44},
  {id: "Red", date: "June 19", shares: 17},
  {id: "Red", date: "June 19", shares: 16},
  {id: "Purple", date: "June 19", shares: 15},
  {id: "Red", date: "June 19", shares: 13},
  {id: "Blue", date: "June 19", shares: 12},
  {id: "Purple", date: "June 19", shares: 10},
  {id: "Blue", date: "June 19", shares: 9},
  {id: "Purple", date: "June 19", shares: 9}
  
  
];
var visualization = d3plus.viz()
  .container("#svg_BarChart3")
  .data(data)
  .type("bar")
  .id("id")
  .x("date")
  .y("shares")
  .draw();

