var svg = d3.select("body").select("#svg_BarChart2");
var data = [
  {id: "Time", date: "June 12", shares: 130},
  {id: "Clashdaily", date: "June 12", shares: 119},
  {id: "Youtube", date: "June 12", shares: 86},
  {id: "PoliticusUSA", date: "June 12", shares: 76},
  {id: "Twitter", date: "June 12", shares: 69},
  {id: "Time", date: "June 12", shares: 68},
  {id: "OccupyDemocrats", date: "June 12", shares: 66},
  {id: "USAToday", date: "June 12", shares: 63},
  {id: "ZeroHedge", date: "June 12", shares: 56},
  {id: "AmericanThinker", date: "June 12", shares: 55},
  {id: "Youtube", date: "June 13", shares: 68},
  {id: "NewYorkTimes", date: "June 13", shares: 59},
  {id: "PJMedia", date: "June 13", shares: 57},
  {id: "WashingtonPost", date: "June 13", shares: 53},
  {id: "NewYorkTimes", date: "June 13", shares: 53},
  {id: "Breitbart", date: "June 13", shares: 44},
  {id: "People", date: "June 13", shares: 29},
  {id: "TheAtlantic", date: "June 13", shares: 28},
  {id: "Twitter", date: "June 13", shares: 25},
  {id: "CNN", date: "June 13", shares: 25},
  {id: "Youtube", date: "June 14", shares: 65},
  {id: "FoxNews", date: "June 14", shares: 31},
  {id: "TheHill", date: "June 14", shares: 24},
  {id: "PJMedia", date: "June 14", shares: 24},
  {id: "NewYorkTimes", date: "June 14", shares: 22},
  {id: "TheAtlantic", date: "June 14", shares: 17},
  {id: "HuffingtonPost", date: "June 14", shares: 17},
  {id: "CBS", date: "June 14", shares: 16},
  {id: "CNN", date: "June 14", shares: 16},
  {id: "WashingtonPost", date: "June 14", shares: 13},
  {id: "Youtube", date: "June 15", shares: 103},
  {id: "Mashable", date: "June 15", shares: 98},
  {id: "BBC", date: "June 15", shares: 75},
  {id: "TheHill", date: "June 15", shares: 75},
  {id: "TheNewCivilRightsMovement", date: "June 15", shares: 59},
  {id: "WashingtonPost", date: "June 15", shares: 42},
  {id: "NewYorkTimes", date: "June 15", shares: 35},
  {id: "VanityFair", date: "June 15", shares: 29},
  {id: "MSNBC", date: "June 15", shares: 23},
  {id: "Advocate", date: "June 15", shares: 22},
  {id: "Youtube", date: "June 16", shares: 77},
  {id: "VanityFair", date: "June 16", shares: 57},
  {id: "PamelaGeller", date: "June 16", shares: 33},
  {id: "Snopes", date: "June 16", shares: 28},
  {id: "NewYorkTimes", date: "June 16", shares: 21},
  {id: "WashingtonPost", date: "June 16", shares: 20},
  {id: "Breitbart", date: "June 16", shares: 20},
  {id: "BipartisanReport", date: "June 16", shares: 20},
  {id: "ConservativeReview", date: "June 16", shares: 19},
  {id: "TheNewCivilRightsMovement", date: "June 16", shares: 18},
  {id: "Time", date: "June 17", shares: 97},
  {id: "Youtube", date: "June 17", shares: 78},
  {id: "Breitbart", date: "June 17", shares: 36},
  {id: "Breitbart", date: "June 17", shares: 35},
  {id: "Snopes", date: "June 17", shares: 21},
  {id: "PamelaGeller", date: "June 17", shares: 20},
  {id: "HuffingtonPost", date: "June 17", shares: 18},
  {id: "CNN", date: "June 17", shares: 16},
  {id: "WashingtonPost", date: "June 17", shares: 14},
  {id: "PoliticusUSA", date: "June 17", shares: 14},
  {id: "Youtube", date: "June 18", shares: 61},
  {id: "CNN", date: "June 18", shares: 41},
  {id: "Time", date: "June 18", shares: 21},
  {id: "NBC", date: "June 18", shares: 20},
  {id: "HuffingtonPost", date: "June 18", shares: 19},
  {id: "FoxNews", date: "June 18", shares: 18},
  {id: "HuffingtonPost", date: "June 18", shares: 17},
  {id: "Breitbart", date: "June 18", shares: 15},
  {id: "TheGatewayPundit", date: "June 18", shares: 12},
  {id: "TheGatewayPundit", date: "June 18", shares: 11},
  {id: "FoxNews", date: "June 19", shares: 87},
  {id: "Youtube", date: "June 19", shares: 44},
  {id: "InfoWars", date: "June 19", shares: 17},
  {id: "FoxNews", date: "June 19", shares: 16},
  {id: "ABC", date: "June 19", shares: 15},
  {id: "PoliticusUSA", date: "June 19", shares: 13},
  {id: "HillaryClinton", date: "June 19", shares: 12},
  {id: "NBC", date: "June 19", shares: 10},
  {id: "HuffingtonPost", date: "June 19", shares: 9},
  {id: "NBC", date: "June 19", shares: 9}
  
  
];
var visualization = d3plus.viz()
  .container("#svg_BarChart2")
  .data(data)
  .type("bar")
  .id("id")
  .x("date")
  .y("shares")
  .draw();
